#!/bin/bash
set -euo pipefail

PG_CONNECTION_STRING=postgres://raifyuma:4Npu8xvGRcRXzXjSlA2nZuBzi2uTuhxl@rajje.db.elephantsql.com:5432/raifyuma;

connect() {
    echo "Connecting to postgres database";
    psql -d $PG_CONNECTION_STRING;
}

migrate() {
    tsc ./src/db/migrate.ts --outDir ./dist && PG_HOST=rajje.db.elephantsql.com PG_USER=raifyuma PG_PASSWORD=4Npu8xvGRcRXzXjSlA2nZuBzi2uTuhxl PG_DATABASE=raifyuma PG_PORT=5432 node ./dist/migrate.js;
}

"$@"